### PR TITLE
Main

### PR DESCRIPTION
**Pull request by pietrop**

### CODE REVIEW

**Comment by pietrop** [comment]
created by mistake, sorry

**Comment by adamduncan** [comment]
No problemo 👍

**Comment by pietrop** [comment]
Also thank you soo much @adamduncan for making this example. I tweaked it and made a starter template repo for some of my projects 

https://pietropassarelli.com/11ty-auto-navigation-book-template

https://github.com/pietrop/11ty-auto-navigation-book-template

And this is the first use of it 

https://pietropassarelli.com/how-to-craft-compelling-stories-out-of-audio-video-interviews/


Thanks again 🙏

**Comment by adamduncan** [comment]
That is awesome to hear, @pietrop. Nice work on the starter kit!

It's been a while since I've revisited the concept. Always open to suggestions and PRs if you find improvements to the approach 🙂

**Pull request closed without merging**
